services:
  database:
    image: docker-compose-exercise-database
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: movie123
    networks:
      - docker-compose-exercise

  webapp:
    image: docker-compose-exercise-webapp
    container_name: webapp
    ports:
      - "8080:80"
    networks:
      - docker-compose-exercise
    depends_on:
      - database

networks:
  docker-compose-exercise:
    driver: bridge

