FROM node:18-alpine

RUN npm install -g serve

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN chmod +x ./node_modules/.bin/vite

RUN npm run build

EXPOSE 3000

CMD ["serve", "-s", "dist", "-l", "3000"]

